server:
  port: 8081

dubbo:
  application:
    name: consumer
  registry:
    address: zookeeper://127.0.0.1:2181
  monitor:
    protocol: registry
  web:
    # 静态资源处理
    resources:
      # 启动默认静态资源处理。默认启动
      add-mappings: true
      cache:
        cachecontrol:
          # 缓存相应时间，单位秒
          max-age: 3600
      chain:
        # 资源链启动缓存，默认启动
        cache: true
        # 启动资源链，默认禁止
        enabled: true
        # 启动压缩资源
        compressed: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/dubbo_demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
    username: root
    password: liyinjian320623,


